controllers:
  resource: ../src/Controller/
  type: attribute

app_home:
  path: /
  controller: App\Controller\HomeController::home

admin_app_allVehicules:
  path: /admin/vehicules
  controller: App\Controller\VehiculeController::adminVehicules

app_add:
  path: /ajout-vehicule
  controller: App\Controller\VehiculeController::add

admin_app_update:
  path: /admin/vehicule/{id}
  controller: App\Controller\VehiculeController::update
  requirements:
    id: '\d+'

app_delete:
  path: /delete_vehicule_{id}
  controller: App\Controller\VehiculeController::delete
  requirements:
    id: '\d+'

app_select:
  path: /select_vehicule_{id}
  controller: App\Controller\VehiculeController::select
  requirements:
    id: '\d+'
